# server configuration
server:
  port: 9191

# endpoint configuration
endpoints:
  shutdown:
    enabled: true

# database configuration
spring:
  jpa:
    show-sql: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false

  datasource:
    url: ${GATEWAY_SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/messagegateway}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:skdcnwauicn2ucnaecasdsajdnizucawencascdca}
    driver-class-name: com.mysql.cj.jdbc.Driver

# Status Callback configuration for Twilio. Port will be taken from server configuration
hostconfig:
  host: ${HOSTCONFIG_HOST:b2a1-102-218-39-110.ngrok-free.app}
  protocol: ${HOSTCONFIG_PROTOCOL:https}

callbackconfig:
  host: ${CALLBACKCONFIG_HOST:0.0.0.0}
  protocol: ${CALLBACKCONFIG_PROTOCOL:http}
  port: ${CALLBACKCONFIG_PORT:5000}

application:
  version: 1.0.0

management:
  endpoint:
    health:
      probes:
        enabled: true
      liveness:
        enabled: true
      readiness:
        enabled: true

providerSource:
  fromdatabase: disabled
  fromyml: enabled

providerKeys:
  telerivetApiKey: eKiC1_JWdKy7eaTGQFHxXXjXjacr60W9Zntl
  telerivetProjectId: PJ5ff552ce01d2978c

provider:
  enabled: true
  id: 2

operationsconfig:
  tenantid: "Fineract-Platform-TenantId"
  tenantidvalue : "default"
  tenantappkey: "Fineract-Tenant-App-Key"
  tenantappvalue: "123456543234abdkdkdkd"


logging:
  level:
    org:
      apache:
        camel=DEBUG:
    root: INFO


camel:
  server-port: 5009
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true
zeebe:
  client:
    max-execution-threads: 100
    number-of-workers: 5
    evenly-allocated-max-jobs: "#{${zeebe.client.max-execution-threads} / ${zeebe.client.number-of-workers}}"
    ttl: 30000
    security:
      plaintext: true
  broker:
#    contactpoint: "zeebe-zeebe-gateway:26500"
    contactpoint: "${ZEEBE_BROKER_CONTACTPOINT:localhost:26500}"
  worker:
    timer: "PT15S"
    retries: 3
